import HONGKONG_GOVERNMENT_FACILITIES from './HONGKONG_GOVERNMENT_FACILITIES'
import HONGKONG_GOVERNMENT_UNITS_BUSES from './HONGKONG_GOVERNMENT_UNITS_BUSES'
import HONGKONG_GOVERNMENT_UNITS_CARS from './HONGKONG_GOVERNMENT_UNITS_CARS'
import HONGKONG_GOVERNMENT_UNITS_CROWDCONTROL from './HONGKONG_GOVERNMENT_UNITS_CROWDCONTROL'
import HONGKONG_GOVERNMENT_UNITS_MEDICS from './HONGKONG_GOVERNMENT_UNITS_MEDICS'
import HONGKONG_PROTESTERS_UNITS_CARS from './HONGKONG_PROTESTERS_UNITS_CARS'
import HONGKONG_PROTESTERS_UNITS_CROWDS from './HONGKONG_PROTESTERS_UNITS_CROWDS'
import HONGKONG_PROTESTERS_UNITS_CROWDCONTROL from './HONGKONG_PROTESTERS_UNITS_CROWDCONTROL'
import HONGKONG_PROTESTERS_UNITS_MEDICS from './HONGKONG_PROTESTERS_UNITS_MEDICS'

const FEATURE_COLLECTIONS = {
  'Hong Kong > Government > Facilities': HONGKONG_GOVERNMENT_FACILITIES,
  'Hong Kong > Government > Units > Buses': HONGKONG_GOVERNMENT_UNITS_BUSES,
  'Hong Kong > Government > Units > Cars': HONGKONG_GOVERNMENT_UNITS_CARS,
  'Hong Kong > Government > Units > Crowd Control': HONGKONG_GOVERNMENT_UNITS_CROWDCONTROL,
  'Hong Kong > Government > Units > Medics': HONGKONG_GOVERNMENT_UNITS_MEDICS,
  'Hong Kong > Protesters > Units > Cars': HONGKONG_PROTESTERS_UNITS_CARS,
  'Hong Kong > Protesters > Units > Crowds': HONGKONG_PROTESTERS_UNITS_CROWDS,
  'Hong Kong > Protesters > Units > Crowd Control': HONGKONG_PROTESTERS_UNITS_CROWDCONTROL,
  'Hong Kong > Protesters > Units > Medics': HONGKONG_PROTESTERS_UNITS_MEDICS
}

export default FEATURE_COLLECTIONS
